[package]
name = "planc"
version = "0.1.0"
edition = "2018"

[dependencies]
clap = "2.33"
env_logger = "0.9"
http = "0.2"
hyper = { version = "0.14", features = ["server", "http1", "tcp"] }
include_dir = "0.6"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.11", features = ["full"] }
