[package]
name = "planc-protocol"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }

[features]
default = []
client = []
server = []
