name: ci

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm install
      - run: npm run build
      - uses: actions/upload-artifact@v5
        with:
          name: frontend
          path: web/dist

  build:
    runs-on: ubuntu-latest
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v6
        with:
          name: frontend
          path: web/dist
      - run: cargo build --verbose
      - run: cargo test --verbose

  build_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v6

  clippy:
    runs-on: ubuntu-latest
    needs: [build_frontend]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/download-artifact@v6
        with:
          name: frontend
          path: web/dist
      - run: cargo clippy --verbose --all --tests

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: cargo fmt --all -- --check
