name: publish

on:
  push:
    tags:
      - '*'

jobs:

  build_and_publish_docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - id: values
        run: |
          echo "tag=${GITHUB_REF_NAME#v}" >> ${GITHUB_OUTPUT}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: 'rwie/planc:${{ steps.values.outputs.tag }}'
